<?php
 /**
 * GoMage Ads & Promo Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>

<style type="text/css"> 
	#window_content{width: 98% !important;}
</style>

<?php $_element = $this->getElement() ?>
<?php if (!$_element->getNoDisplay()): ?>
<tr>
    <td class="label"><label for="window_content"><?php echo $_element->getLabel(); ?></label></td>
    <td class="value" style="width: 100%;">
        <?php echo trim($_element->getElementHtml()) ?>
	</td>
</tr>
<?php endif; ?>
