<?php
 /**
 * GoMage Ads & Promo Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.2
 * @since        Class available since Release 1.0
 */
 ?>

<?php foreach ($this->getAdspromoImageItems() as $item): ?>
       
    <div id="gomage-ads-image-container-<?php echo $item->getId(); ?>" class="gomage-ads-image-container" style="<?php echo $item->getAdsImageStyles(); ?>">
      <a href="<?php echo $item->getImageOpenLinkUrl(); ?>"  
             <?php if ($item->getImageOpenLink() == GoMage_Adspromo_Model_Adminhtml_System_Config_Source_Image_Openlink::PROMO_WINDOW): ?>
                   <?php if ($item->getWindowShow() == GoMage_Adspromo_Model_Adminhtml_System_Config_Source_Window_Show::MOUSE_CLICK): ?>                   		                   		
                        onclick="ShowAdsWindow('gomage-ads-window-<?php echo $item->getId(); ?>'); return false;"
                   <?php endif; ?>
             <?php else: ?>
             	   onclick="AddAdsClick(<?php echo $item->getId(); ?>, 0); return false;"  		
             <?php endif; ?> >
    	<img alt="<?php echo $this->stripTags($item->getTitle(), null, true) ?>" id="gomage-ads-baseimage-<?php echo $item->getId(); ?>" class="gomage-ads-baseimage" src="<?php echo $item->getBaseImageUrl(); ?>" style="<?php echo $item->getAdsImageStyles(); ?> width: <?php echo $item->getData('effect_width'); ?>px; height: <?php echo $item->getData('effect_height'); ?>px;" />
    	<?php if ($item->getAlternativeImageUrl()): ?>
    		<img alt="<?php echo $this->stripTags($item->getTitle(), null, true) ?>" id="gomage-ads-alternativeimage-<?php echo $item->getId(); ?>" style="display: none; <?php echo $item->getAdsImageStyles(); ?>  width: <?php echo $item->getData('alt_effect_width'); ?>px; height: <?php echo $item->getData('alt_effect_height'); ?>px;" class="gomage-ads-alternativeimage" src="<?php echo $item->getAlternativeImageUrl(); ?>" />
    	<?php endif; ?>	
      </a>	
    </div>    
  
<?php endforeach; ?>

<script type="text/javascript">
//<![CDATA[
    var gomage_image_configs = <?php echo $this->getAdsImageConfigs(); ?>; 
    var gomage_window_configs = <?php echo $this->getAdsWindowConfigs(); ?>;
    var gomage_ads_click_url = '<?php echo $this->getUrl('adspromo/index/click'); ?>';
//]]>
</script>